# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/digilent-xdc-master/Basys-3-Master.xdc

# Block Designs: bd/main/main.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==main || ORIG_REF_NAME==main} -quiet] -quiet

# IP: bd/main/ip/main_clk_wiz_0_0/main_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==main_clk_wiz_0_0 || ORIG_REF_NAME==main_clk_wiz_0_0} -quiet] -quiet

# IP: bd/main/ip/main_axi_uartlite_0_0/main_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==main_axi_uartlite_0_0 || ORIG_REF_NAME==main_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/main/ip/main_microblaze_0_0/main_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==main_microblaze_0_0 || ORIG_REF_NAME==main_microblaze_0_0} -quiet] -quiet

# IP: bd/main/ip/main_mdm_1_0/main_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==main_mdm_1_0 || ORIG_REF_NAME==main_mdm_1_0} -quiet] -quiet

# IP: bd/main/ip/main_rst_clk_wiz_0_100M_0/main_rst_clk_wiz_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==main_rst_clk_wiz_0_100M_0 || ORIG_REF_NAME==main_rst_clk_wiz_0_100M_0} -quiet] -quiet

# IP: bd/main/ip/main_microblaze_0_axi_periph_0/main_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==main_microblaze_0_axi_periph_0 || ORIG_REF_NAME==main_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/main/ip/main_dlmb_v10_0/main_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==main_dlmb_v10_0 || ORIG_REF_NAME==main_dlmb_v10_0} -quiet] -quiet

# IP: bd/main/ip/main_ilmb_v10_0/main_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==main_ilmb_v10_0 || ORIG_REF_NAME==main_ilmb_v10_0} -quiet] -quiet

# IP: bd/main/ip/main_dlmb_bram_if_cntlr_0/main_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==main_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==main_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/main/ip/main_ilmb_bram_if_cntlr_0/main_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==main_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==main_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/main/ip/main_lmb_bram_0/main_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==main_lmb_bram_0 || ORIG_REF_NAME==main_lmb_bram_0} -quiet] -quiet

# XDC: bd/main/main_ooc.xdc
