# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/part1_hello_world/part1_hello_world.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==part1_hello_world || ORIG_REF_NAME==part1_hello_world} -quiet] -quiet

# IP: bd/part1_hello_world/ip/part1_hello_world_axi_gpio_0_0/part1_hello_world_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==part1_hello_world_axi_gpio_0_0 || ORIG_REF_NAME==part1_hello_world_axi_gpio_0_0} -quiet] -quiet

# IP: bd/part1_hello_world/ip/part1_hello_world_clk_wiz_0_0/part1_hello_world_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==part1_hello_world_clk_wiz_0_0 || ORIG_REF_NAME==part1_hello_world_clk_wiz_0_0} -quiet] -quiet

# IP: bd/part1_hello_world/ip/part1_hello_world_axi_uartlite_0_0/part1_hello_world_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==part1_hello_world_axi_uartlite_0_0 || ORIG_REF_NAME==part1_hello_world_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/part1_hello_world/ip/part1_hello_world_microblaze_0_0/part1_hello_world_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==part1_hello_world_microblaze_0_0 || ORIG_REF_NAME==part1_hello_world_microblaze_0_0} -quiet] -quiet

# IP: bd/part1_hello_world/ip/part1_hello_world_mdm_1_0/part1_hello_world_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==part1_hello_world_mdm_1_0 || ORIG_REF_NAME==part1_hello_world_mdm_1_0} -quiet] -quiet

# IP: bd/part1_hello_world/ip/part1_hello_world_rst_clk_wiz_0_100M_0/part1_hello_world_rst_clk_wiz_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==part1_hello_world_rst_clk_wiz_0_100M_0 || ORIG_REF_NAME==part1_hello_world_rst_clk_wiz_0_100M_0} -quiet] -quiet

# IP: bd/part1_hello_world/ip/part1_hello_world_microblaze_0_axi_periph_0/part1_hello_world_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==part1_hello_world_microblaze_0_axi_periph_0 || ORIG_REF_NAME==part1_hello_world_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/part1_hello_world/ip/part1_hello_world_xbar_0/part1_hello_world_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==part1_hello_world_xbar_0 || ORIG_REF_NAME==part1_hello_world_xbar_0} -quiet] -quiet

# IP: bd/part1_hello_world/ip/part1_hello_world_dlmb_v10_0/part1_hello_world_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==part1_hello_world_dlmb_v10_0 || ORIG_REF_NAME==part1_hello_world_dlmb_v10_0} -quiet] -quiet

# IP: bd/part1_hello_world/ip/part1_hello_world_ilmb_v10_0/part1_hello_world_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==part1_hello_world_ilmb_v10_0 || ORIG_REF_NAME==part1_hello_world_ilmb_v10_0} -quiet] -quiet

# IP: bd/part1_hello_world/ip/part1_hello_world_dlmb_bram_if_cntlr_0/part1_hello_world_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==part1_hello_world_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==part1_hello_world_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/part1_hello_world/ip/part1_hello_world_ilmb_bram_if_cntlr_0/part1_hello_world_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==part1_hello_world_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==part1_hello_world_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/part1_hello_world/ip/part1_hello_world_lmb_bram_0/part1_hello_world_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==part1_hello_world_lmb_bram_0 || ORIG_REF_NAME==part1_hello_world_lmb_bram_0} -quiet] -quiet

# XDC: bd/part1_hello_world/part1_hello_world_ooc.xdc
